### PR TITLE
Maintenance

### LINKED ISSUE #1: Maintenance
This plugin is used by the UserFrosting assets pipeline, and I'm hoping to perform some maintenance and optimisations on this package.
* Replacing deprecated `gulp-util` with [`plugin-error`](https://www.npmjs.com/package/plugin-error), [`gulplog`](https://www.npmjs.com/package/gulplog), and [`ansi-colors`](https://www.npmjs.com/package/ansi-colors)
* Updating `globby` from v5 to the current v11
* Revising logic such that `Vinyl` instances don't need to be retained (this bottleneck introduces unnecessary memory pressure and depending on the stream increases total time, the same sort of limitation I recently addressed in https://github.com/userfrosting/gulp-uf-bundle-assets v4).

Before I start, I'm just looking to see if there is any indication that repo isn't dead (no activity in 4 years as best I can tell) as I'd prefer not to perform a hard fork when the outcome would be a functionally identical package.

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
Resolves https://github.com/hh10k/gulp-prune/issues/1

Changes made are;
* Migrating off deprecated `gulp-util`.
* Updating `globby`, `eslint`, etc
* Addition of guard to ensure only `Vinyl` instances are processed (improves reliability when a plugin earlier in the stream outputs incompatible chunks)
* Added TypeScript types definition generation (uses type information from JSDoc, which has been added). Integration test pending.
* Extracted input validation into function wrapper so that `PruneTransform` is focused solely on removal of untouched files.
* Migrating some promises to async function syntax (less verbose, easier to follow logic)
* Improvements to handling of file system errors. This will address an issue where gulp-prune appears to have completed following the report of an erorr, but still has many pending deletions sitting in the JS event loop queue resulting in the process appearing to hang. It may be desirable to handle each deletion sequentially in the future so that there is no delay when an issue is encountered. Such an approach may offer better overall performance as well, as currently potentially thousands of unresolved promises are created in a short span.
* Updated Travis CI to use current LTS releases.
* Added `.editorconfig` to ensure supporting IDEs use 2 space tabbing and `lf` line endings.
* Added changelog file. (I recommend using a tool like https://www.npmjs.com/package/changelog-updater to automate version updates, depending on your release process).

In https://github.com/hh10k/gulp-prune/issues/1 I had mentioned optimising this package. It seems at the time I had misread the source, the optimisation I had in mind was already implemented.

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
Pinging @hh10k

**Comment by Tomalak** [comment]
...I see somebody already had the same idea I had (#3), but did quite a bit more work. Oh well. :)

**Comment by Silic0nS0ldier** [comment]
Yep. I've fallen for that trap myself in the past. I should probably give the deps in the PR a bump at this point. Don't suppose you know of a way to reach @hh10k ?

**Comment by Tomalak** [comment]
No, I have just had a use for this Gulp plugin yesterday, so I quickly forked it and fixed the issues I saw. Given that it's not been updated for 5 years here, seem that priorities have ... shifted.

**Comment by Silic0nS0ldier** [comment]
I'm trying to avoid it but its looking more and more like I'll be making a permanent fork. Should that happen, I'll post an update here.

**Comment by Silic0nS0ldier** [comment]
Decision has been made, I'll be creating a permanent fork.

I've transferred my fork over to the @userfrosting org, and once I've regained admin powers over the repo will be renaming master (so this PR can stay open) I will be bring the repo in line with other JS packages under the org. In practical terms that means;

1. Switching from Travis to Github Actions.
2. Switching from JS with TS compliant JSDoc to plain TS.
3. Implementing API docs generation and public API surface checks.
4. Automated dependency updates (releases still manual).
5. Adding code coverage checks.
6. Raising NodeJS minimum version (v10 is about to hit EOL, should eliminate a polyfill).
7. Refactoring code to use native ESM.
8. Switching from `fancy-log` to `ts-log` (built-in logging may return later once [@userfrosting/ts-log-adapter-gulplog](https://github.com/userfrosting/ts-log-adapter-gulplog) is stable).

Likely not exactly what people are looking for, but ultimately consistency across the packages I maintain is essential for my sanity (and for there to be any hope of automating a lot of maintenance later on).

I'll add another comment once the package is live.

**Comment by hh10k** [comment]
@Silic0nS0ldier If you like I can transfer the gulp-prune npm package over to you.  Which user should I add as a maintainer?

**Comment by Silic0nS0ldier** [comment]
@hh10k If you are happy to, ownership transfer sounds good. My NPM username is `siliconsoldier`.

**Comment by hh10k** [comment]
Thanks for taking it over! I'm obviously not up to maintaining it at the moment.

**Comment by Silic0nS0ldier** [comment]
I've pushed out a release candidate. https://www.npmjs.com/package/gulp-prune/v/1.0.0-rc.0
cc @Tomalak 

@hh10k Final request. Could you transfer the repository to my account? Its ultimate destination will be the @userfrosting org, but as I have already transferred my fork into the org there is some juggling to be done. This will ensure that existing links to the repo will be correctly redirected (and will resolve some annoying workflow issues on Github which always assumes a forked repo wants to merge upstream).

**Pull request closed without merging**
